# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-21 21:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artefact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=254)),
                ('history', models.TextField()),
                ('description', models.TextField()),
                ('century', models.DecimalField(decimal_places=0, max_digits=3)),
                ('era', models.CharField(choices=[('AD', 'Anno Domini'), ('BC', 'Before Christ')], max_length=2)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sold', models.BooleanField(default=False)),
            ],
        ),
    ]
