# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-23 20:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0005_auto_20191123_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='despatch_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artefact',
            name='despatched',
            field=models.BooleanField(default=False),
        ),
    ]
