# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-23 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0006_auto_20191123_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='despatch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
