# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-28 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0009_auto_20191126_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='name',
            field=models.CharField(default='', help_text='Name Of Artefact Being Sold', max_length=254),
        ),
    ]
