# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-31 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0011_auto_20191231_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artefact',
            name='century',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='era',
            field=models.CharField(blank=True, choices=[('AD', 'Anno Domini'), ('BC', 'Before Christ')], max_length=2),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='name',
            field=models.CharField(blank=True, default='', max_length=254),
        ),
    ]
