# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-03 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0012_auto_20191231_1800'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artefact',
            name='image',
        ),
        migrations.AlterField(
            model_name='artefact',
            name='century',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='era',
            field=models.CharField(choices=[('AD', 'Anno Domini'), ('BC', 'Before Christ')], max_length=2),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='history',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artefact',
            name='name',
            field=models.CharField(default='', max_length=254),
        ),
    ]
