# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-01-03 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artefacts', '0013_auto_20200103_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='artefact',
            name='image',
            field=models.ImageField(blank=True, upload_to='static'),
        ),
    ]
