# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-10-23 21:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artefacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('delivery_full_name', models.CharField(max_length=60)),
                ('delivery_street_address1', models.CharField(max_length=40)),
                ('delivery_street_address2', models.CharField(max_length=40)),
                ('delivery_town_or_city', models.CharField(max_length=40)),
                ('delivery_county', models.CharField(max_length=40)),
                ('delivery_country', models.CharField(max_length=40)),
                ('delivery_postcode', models.CharField(blank=True, max_length=20)),
                ('delivery_phone_number', models.CharField(max_length=20)),
                ('delivery_email', models.CharField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('artefact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artefacts.Artefact')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.Order')),
            ],
        ),
    ]
