# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-21 23:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_auto_20191117_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
