# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-11-25 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0003_auto_20191121_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.FloatField(default=0.0),
        ),
    ]
