# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-12-31 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0004_auto_20191125_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='bid',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
